library(tidyr)
library(dplyr)
library(plyr)
library(Seurat)
library(patchwork)
library(reshape2)
library(pheatmap)
library(ggplot2)
library(gridExtra)
library(grid)
library(limma)
library(batchelor)
library(scran)
library(scater)
# library(Biocmanager)

setwd("/share/quonlab/workspaces/fangyiwang/gastric cancer/upper gastrointestinal tract")

ugi.data <- read.delim("data_CellReports.tsv.gz")
